name: My first Workflow

on: 
  push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Genrate My first Github Action
        run: | 
             echo "Hello SirGeorge, this is your first action"
             ls
             cat README.md



      # - name: List the files
      #   run: | 
      #        ls

      # - name: Read the README file
      #   run: cat README.md
