name: Generate ASCII artwork

on: 
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update and Install the cowsay program 
        run: sudo apt update && sudo apt install cowsay -y


      - name: Execute the cowsay program
        run:  cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt

      - name: Test File exist
        run: grep -f "dragon" dragon.txt

      - name: Read the file
        run:  cat dragon.txt
    
      - name: Checkout repo file 
        run: ls 

        